// -*- mode: C++; c-file-style: "virtutech-c++" -*-

/*
  © 2025 Intel Corporation

  This software and the related documents are Intel copyrighted materials, and
  your use of them is governed by the express license under which they were
  provided to you ("License"). Unless the License provides otherwise, you may
  not use, modify, copy, publish, distribute, disclose or transmit this software
  or the related documents without Intel's prior written permission.

  This software and the related documents are provided as is, with no express or
  implied warranties, other than those that are expressly stated in the License.
*/

// This file is generated by the script bin/gen-cc-interface

#ifndef SIMICS_CPP_MODEL_IFACE_DEVICE_IDENTIFICATION_H
#define SIMICS_CPP_MODEL_IFACE_DEVICE_IDENTIFICATION_H

#include "simics/model-iface/device-identification.h"

#include <simics/detail/conf-object-util.h>  // get_interface
#include <simics/iface/interface-info.h>

namespace simics {
namespace iface {

class DeviceIdentificationInterface {
  public:
    using ctype = device_identification_interface_t;

    // Function override and implemented by user
    virtual const char * get_id(const char *key) = 0;
    virtual const char * get_key(unsigned int index) = 0;

    // Function convert C interface call to C++ interface call
    class FromC {
      public:
        static const char * get_id(conf_object_t *obj, const char *key) {
            return detail::get_interface<DeviceIdentificationInterface>(obj)->get_id(key);
        }
        static const char * get_key(conf_object_t *obj, unsigned int index) {
            return detail::get_interface<DeviceIdentificationInterface>(obj)->get_key(index);
        }
    };

    // Function convert C++ interface call to C interface call
    class ToC {
      public:
        ToC() : obj_(nullptr), iface_(nullptr) {}
        ToC(conf_object_t *obj, const DeviceIdentificationInterface::ctype *iface)
            : obj_(obj), iface_(iface) {}

        const char * get_id(const char *key) const {
            return iface_->get_id(obj_, key);
        }
        const char * get_key(unsigned int index) const {
            return iface_->get_key(obj_, index);
        }

        const DeviceIdentificationInterface::ctype *get_iface() const {
            return iface_;
        }

      private:
        conf_object_t *obj_;
        const DeviceIdentificationInterface::ctype *iface_;
    };

    class Info : public InterfaceInfo {
      public:
        // InterfaceInfo
        std::string name() const override { return DEVICE_IDENTIFICATION_INTERFACE; }
        const interface_t *cstruct() const override {
            static constexpr DeviceIdentificationInterface::ctype funcs {
                FromC::get_id,
                FromC::get_key,
            };
            return &funcs;
        }
    };
};

}  // namespace iface
}  // namespace simics

#endif
