# -*- Makefile -*-

# © 2010 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

MODULE_CLASSES = cpumode_software_mapper cpumode_software_tracker \
	cpumode_software_tracker_comp

PYTHON_FILES = cpumode_software_tracker.py module_load.py \
	cpumode_composition.py simics_start.py
THREAD_SAFE = yes
SIMICS_API = latest

include $(MODULE_MAKEFILE)
