#!/bin/bash

# © 2012 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.


# The script unloads VMXMON kernel module.
# Please follow this style guide when updating the script:
# https://google.github.io/styleguide/shellguide.html

set -u  # To catch errors early let's treat unset variables as errors.


if [[ -n "${1:-}" ]]; then
    case "$1" in
        --help|-h|*) echo "Usage: $0" ; exit 0 ;;
    esac
fi

SUDO="sudo"
if [[ "${UID}" == "0" ]]; then
    SUDO=""
fi
readonly SUDO

function unload() {
    local x
    for x in "$@" ; do
        if ! /sbin/lsmod | grep "${x}" >& /dev/null ; then
            echo "Module ${x} is not loaded"
            continue
        fi
        $SUDO /sbin/rmmod "${x}" || {
            echo "Failed to unload kernel module ${x}"
            continue
        }
        echo "Module ${x} unloaded"
    done
    return 0
}

unload vmxmon
