# -*- Makefile -*-

# © 2010 Intel Corporation

# Simics module makefile

MODULE_COMPONENTS := empty_components
SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = empty_components.py module_load.py

include $(MODULE_MAKEFILE)
