// -*- mode: C++; c-file-style: "virtutech-c++" -*-

/*
  © 2025 Intel Corporation

  This software and the related documents are Intel copyrighted materials, and
  your use of them is governed by the express license under which they were
  provided to you ("License"). Unless the License provides otherwise, you may
  not use, modify, copy, publish, distribute, disclose or transmit this software
  or the related documents without Intel's prior written permission.

  This software and the related documents are provided as is, with no express or
  implied warranties, other than those that are expressly stated in the License.
*/

// This file is generated by the script bin/gen-cc-interface

#ifndef SIMICS_CPP_SIMULATOR_IFACE_TABLE_H
#define SIMICS_CPP_SIMULATOR_IFACE_TABLE_H

#include "simics/simulator-iface/table.h"

#include <simics/detail/conf-object-util.h>  // get_interface
#include <simics/iface/interface-info.h>

namespace simics {
namespace iface {

class TableInterface {
  public:
    using ctype = table_interface_t;

    // Function override and implemented by user
    virtual attr_value_t data() = 0;
    virtual attr_value_t properties() = 0;

    // Function convert C interface call to C++ interface call
    class FromC {
      public:
        static attr_value_t data(conf_object_t *obj) {
            return detail::get_interface<TableInterface>(obj)->data();
        }
        static attr_value_t properties(conf_object_t *obj) {
            return detail::get_interface<TableInterface>(obj)->properties();
        }
    };

    // Function convert C++ interface call to C interface call
    class ToC {
      public:
        ToC() : obj_(nullptr), iface_(nullptr) {}
        ToC(conf_object_t *obj, const TableInterface::ctype *iface)
            : obj_(obj), iface_(iface) {}

        attr_value_t data() const {
            return iface_->data(obj_);
        }
        attr_value_t properties() const {
            return iface_->properties(obj_);
        }

        const TableInterface::ctype *get_iface() const {
            return iface_;
        }

      private:
        conf_object_t *obj_;
        const TableInterface::ctype *iface_;
    };

    class Info : public InterfaceInfo {
      public:
        // InterfaceInfo
        std::string name() const override { return TABLE_INTERFACE; }
        const interface_t *cstruct() const override {
            static constexpr TableInterface::ctype funcs {
                FromC::data,
                FromC::properties,
            };
            return &funcs;
        }
    };
};

}  // namespace iface
}  // namespace simics

#endif
