# -*- Makefile ; coding: utf-8 -*-

# © 2010 Intel Corporation

# Simics module makefile

MODULE_CLASSES = empty_device_tlm2

SRC_FILES = empty-device-tlm2.cc simics-init.cc
PYTHON_FILES = module_load.py

SIMICS_API := 7
THREAD_SAFE = yes
SYSTEMC = yes

# Prefer Visual Studio on Windows
COMPILERS = cl gcc

include $(MODULE_MAKEFILE)
