
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0
RAW_SIMICS_MODEL_BUILDER=/home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0
RAW_PYTHON_PKG=/home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-python-7.10.0

RAW_SIMICS_PACKAGE_LIST=/home/debian/Sterowniki-dla-systemu-Linux/lab2/simics-projects/proj1/.package-list

INCLUDE_PATHS = /home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0/src/include
CXX_INCLUDE_PATHS = /home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0/linux64/api
DML_INCLUDE_PATHS = /home/debian/Sterowniki-dla-systemu-Linux/lab2/simics/simics-7.38.0/linux64/bin/dml/api
HOST_TYPE = linux64
