# -*- Makefile -*-

# © 2016 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

# Simics module makefile

MODULE_COMPONENTS := txt_console_comp gfx_console_comp

SIMICS_API := latest
THREAD_SAFE:= yes
PYTHON_FILES = console_components.py module_load.py
SRC_IMAGES = textcon.png graphcon.png

include $(MODULE_MAKEFILE)
