# -*- Makefile -*-

# © 2017 Intel Corporation

# Simics module makefile

MODULE_CLASSES = empty_instrumentation_filter
SRC_FILES = empty-instrumentation-filter.c
PYTHON_FILES = simics_start.py module_load.py
SIMICS_API := 7
THREAD_SAFE = yes


include $(MODULE_MAKEFILE)
