%YAML 1.2
---
description: Script that creates the training PCIe card.
params:        
  name:
    type: str
    description: Name of the subsystem to create.
    default: training_card
  owner:
    type: str
    description: The name of the system inside of which we create the card.
    required: false
  pcie_slot:
    type: str
    description: The PCIe slot to which to connect the card.
    required: false
  use_behavioral_box:
    type: bool
    description: >-
                 Use the behavioral model of the training device.
                 At the time, there is no firmware box model available.
    default: true
    advanced: 2
  bb_pixel_update_time:
    type: int
    description: Time to account for a pixel update [in subsystem processor clocks].
    default: 17
    advanced: 2    
  bb_toggle_check_interval:
    type: int
    description: Interval between toggle checks [in subsystem processor clocks].
    default: 2000000
    advanced: 2
  clock_frequency:
    type: int
    description: Clock frequency of the processor embedded in the subsystem
    default: 100000000
    advanced: 2    
  output:
    training_card:
      type: str
      output: true

script: "%script%/training-card.yml.include"
...
