// -*- mode: C++; c-file-style: "virtutech-c++" -*-

/*
  © 2025 Intel Corporation

  This software and the related documents are Intel copyrighted materials, and
  your use of them is governed by the express license under which they were
  provided to you ("License"). Unless the License provides otherwise, you may
  not use, modify, copy, publish, distribute, disclose or transmit this software
  or the related documents without Intel's prior written permission.

  This software and the related documents are provided as is, with no express or
  implied warranties, other than those that are expressly stated in the License.
*/

// This file is generated by the script bin/gen-cc-interface

#ifndef SIMICS_CPP_DEVS_COREINT_H
#define SIMICS_CPP_DEVS_COREINT_H

#include "simics/devs/coreint.h"

#include <simics/detail/conf-object-util.h>  // get_interface
#include <simics/iface/interface-info.h>

namespace simics {
namespace iface {

class CoreintInterface {
  public:
    using ctype = coreint_interface_t;

    // Function override and implemented by user
    virtual coreint_reply_t acknowledge(conf_object_t *core) = 0;

    // Function convert C interface call to C++ interface call
    class FromC {
      public:
        static coreint_reply_t acknowledge(conf_object_t *obj, conf_object_t *core) {
            return detail::get_interface<CoreintInterface>(obj)->acknowledge(core);
        }
    };

    // Function convert C++ interface call to C interface call
    class ToC {
      public:
        ToC() : obj_(nullptr), iface_(nullptr) {}
        ToC(conf_object_t *obj, const CoreintInterface::ctype *iface)
            : obj_(obj), iface_(iface) {}

        coreint_reply_t acknowledge(conf_object_t *core) const {
            return iface_->acknowledge(obj_, core);
        }

        const CoreintInterface::ctype *get_iface() const {
            return iface_;
        }

      private:
        conf_object_t *obj_;
        const CoreintInterface::ctype *iface_;
    };

    class Info : public InterfaceInfo {
      public:
        // InterfaceInfo
        std::string name() const override { return COREINT_INTERFACE; }
        const interface_t *cstruct() const override {
            static constexpr CoreintInterface::ctype funcs {
                FromC::acknowledge,
            };
            return &funcs;
        }
    };
};

}  // namespace iface
}  // namespace simics

#endif
