# -*- Makefile -*-

# © 2017 Intel Corporation

# Simics module makefile

PYTHON_FILES = module_load.py simics_start.py

MODULE_CLASSES = empty_tool empty_tool_connection
SRC_FILES += empty-instrumentation-tool.c

SIMICS_API := 7
THREAD_SAFE = yes


include $(MODULE_MAKEFILE)

